---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit
  namespace: rmq
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbit
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbit
subjects:
- kind: ServiceAccount
  name: rabbit
  namespace: rmq