---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit
  namespace: {{NAMESPACE}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbit
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - serviceaccounts
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - namespaces/status
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - get
    - list
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbit
subjects:
- kind: ServiceAccount
  name: rabbit
  namespace: {{NAMESPACE}}